### ISSUE TITLE
Working as standalone reader?

### ISSUE THREAD

**Issue by thehijacker** [nygma2004/RFID_Weigand_MQTT#1]
Hello,

Today I received the same reader as you have. Trying to connect it to my ESP-RFID board just as Wiegand signal receiver. I never receive any card data. It also always beeps that card is not recognised. When I use programming mode to add card the card is accepted and I can hear the relay switching. But still I do not get anything from the Wiegand lines.

Can it work as standalone reader? So it only scans the card, sends its data and do nothing else? I wish for ESP-RFID board to make proper buzzing sound if card is valid and not that RFID reader checks its database or fire the relay.

Have you figured this out when you first tested it?

Thank you for the tips.

Best regards,
Andrej

**Comment by nygma2004** [comment]
I am away from home now, but if you open up the paper manual you have received for the device, there is section 5 in the end of the documentation how to set the device to Wiegang 16 reader module. I think you need to short D1 or D0 to the ground and connect to power. After that disconnect the device wire it to the ESP and it should work.

**Comment by thehijacker** [comment]
Manual is a bit confusing.

D0 to GND for Wiegand 26 and D1 to GND for Wiegand 34. That is clear.

When I power on when D0 or D1 and to GND, green light indeed flashes and stops after few seconds. So I guess it is configured. But then in manual says "click to complete conversion". Not sure what that click is. If I power off and on it is still working the same. Using "internal" database and not sending anything to D0 and D1.

Do you perhaps remember how to store this setting?

Thank you!

**Comment by thehijacker** [comment]
Figured it out. Need to disconnect D0 from GND when it starts blinking. Now reading works.

Did you perhaps looked at other things we can do with it? Like control buzzer and LED, control relay inside, use bell output, etc?

**Comment by nygma2004** [comment]
I am not sure, it is not mentioned anywhere. But I ask the seller and will let you know what the response is.

**Comment by thehijacker** [comment]
Thank you. Let me know if you get answer from him.

Best regards.

**Comment by thehijacker** [comment]
Got reply from seller myself. Does not support beep or LED control over data lines.

We can close this :).
