### ISSUE TITLE
Typo in wiring chart?

### ISSUE THREAD

**Issue by byrnes-patrick** [nygma2004/RFID_Weigand_MQTT#4]
Hi, 

For the iButton it looks like it should be red to D2, green to vcc. I was able to see the trace on the pcb photo. 

Thank you for posting this project, I love playing with it!

**Comment by nygma2004** [comment]
Oh yes, that is correct. red is the data pin and it goes to D2. Green goes to Vcc via a resistor not blow the LED.

Thanks for thins, sorry it took much time.
