### ISSUE TITLE
All Pin Codes return an 'Unknown ID'

### ISSUE THREAD

**Issue by tapd** [nygma2004/RFID_Weigand_MQTT#6]
Hi Csongor,

Firstly thank you for your time & effort on this project, it is saving me some time in doing the same thing. I have finally gotten around to test this out after watching your video months ago and I've encountered an issue with the pin codes. No matter which of the codes in the sample user list I enter at the keypad returns 'Unknown ID'. I changed the incoming code to a string in case that was the issue with no luck. Have you encountered this and could you please give me an indication of where the issue may lie.

Thank you.

**Comment by tapd** [comment]
I think I've worked it out. I'm using a Rosslare keypad in Wiegand 26bit mode and the payload.type is "rfid" even though I'm keying in a pin. So I'm feeding the input through a change node to adjust it. The keyed pin also comes though as a number which I change to a string so that the function node will accept it.

**Comment by nygma2004** [comment]
Sorry, bit lazy in the holiday season. Great that you managed to figure this out. And I am happy to see that it works with other Wiegand readers as well.
