### ISSUE TITLE
RFID reader not outputting wiegand code?

### ISSUE THREAD

**Issue by RobbeM1991** [nygma2004/RFID_Weigand_MQTT#7]
Hi, I bought the exact same Wiegand reader as yours.
But it's not outputting anything on the D0 and D1 lines (don't have a scope to measure though).

**Did you have to configure anything on the reader?**

Chapter 5 says something about:
1) Access control mode
2) Read head mode (Wiegand 26 output)
3) Reading head mode (Wiegand 34 output)
But the translation is not really clear and I'm not sure if I need it.
Especially the the reset function is not clear so I'm hesitating to try something...

Thanks!

**Comment by thehijacker** [comment]
Check here.

https://github.com/nygma2004/RFID_Wiegand_MQTT/issues/1

**Comment by RobbeM1991** [comment]
> Check here.
> 
> #1

I've done exactly that. Connect D0 to GND, restart, disconnect when green light is flashing.
Then it is just blinking red...
But it's working like that! The codes get sent over the D0 and D1 lines!

**Comment by RobbeM1991** [comment]
It seems that I need to add a user first (on the RFID reader), and then it get's recognised when I enter the code.
But no matter which user ID + code i program, it always gets recognised as UID 15 in ESP-RFID...

I wanted the device to just send any code I enter or tag I scan and assign it to a User in ESP-RFID. Is that possible?
