### ISSUE TITLE
Red LED constantly blinking in Wiegand mode

### ISSUE THREAD

**Issue by sglvladi** [nygma2004/RFID_Weigand_MQTT#8]
Hi @nygma2004,

Thanks for the hard work and helpful guide.

I have bought myself the same reader from Amazon (see [here](https://www.amazon.co.uk/gp/product/B08YJGWNCB)), and I am able to read pin codes and card successfully. 

My only issue is that, when in Wiegand mode, the red LED on my reader keeps flashing constantly, which I find a bit annoying. Having checked your Youtube videos, your device doesn't seem to be doing that, and instead the red led stays constantly on. 

Any chance you have any clue about how to disable the blinking? I have posted a question to the seller on Amazon, but thought I'd also reach out here in case they never reply.

Thanks much in advance!

**Comment by nygma2004** [comment]
I don't know why it is happening, but I noticed the same. I am using the same reader in Wiegand mode in a different setup (not with my ESP reader). And it works in that setup, but the red LED also blinks there constantly. The reader still works but I am not sure why it is different in these cases.
The Aliexpress seller was a lot more responsive, maybe you can try contacting them there.

**Comment by sglvladi** [comment]
Thanks @nygma2004. It's good to know that I'm not alone at least. 

Just a note for anyone reading this in the future, the module that has the flashing LED is a 125KHz module. I later bought a 13.56MHz module and this one has the LED steady on.
